name: deployment trails
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: env
    attributes:
      label: Environment
      description: What environment would you like to deploy to?
      options:
        - prod (prod)
        - ute (Default)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: action
    attributes:
      label: What terraform actions are you running?
      multiple: true
      options:
        - destroy
        - plan
        - apply (Default)
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
