name: deployment UTE / Prod
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: Input the application version number to be deployed
      placeholder: v1.12.34
    validations:
      required: false
  - type: dropdown
    id: env
    attributes:
      label: Environment
      description: What environment would you like to deploy to?
      options:
        - prod (prod)
        - ute (Default)
      default: 1
    validations:
      required: true
  - type: checkboxes
    id: infra
    attributes:
      label: Infrat
      description: Set up infra using terraform
      options:
        - label: Set up infra
          required: true
