name: Azure deployments
description: Deploy Storm application to Azure environments.
title: "Deploying storm to Azure environments "
labels: ["deploy"]
projects: ["storm"]
assignees:
  - octocat
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: Input the application version number to be deployed as displayed in placeholder
      placeholder: v1.2.3
    validations:
      required: true
  - type: dropdown
    id: env
    attributes:
      label: Environment
      description: What environment would you like to deploy to?
      options:
        - ite
        - acp
        - prod
      default: 1
    validations:
      required: true