name: Reusable workflow example

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version: 
        required: true
        type: string

jobs:
  application-version:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: first one
      run: |
        echo "inputs.environment : ${{ inputs.environment }}"
    - name: second one
      run: |
        echo "vars.hello_world : ${{ vars.HELLO_WORLD }}"
    - name: version
      run : echo v${{ inputs.version }}

    - name: get latest release
      run: gh release list --jq '.[] | select(.isLatest) | .tagName' --json isLatest,tagName
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: download release version
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        ISSUE: ${{ github.event.issue.html_url }}
      run: gh release download v1.1.2

    - name: check if file is downloaded
      run : ls