name: Reusable workflow example

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version: 
        required: true
        type: string

jobs:
  application-version:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: first one
      run: |
        echo "inputs.environment : ${{ inputs.environment }}"
    - name: second one
      run: |
        echo "vars.hello_world : ${{ vars.HELLO_WORLD }}"
    - name: version
      run : echo ${{ inputs.version }}
    - name: download release version
      env: 
        GH_TOKEN: $${{ secrets.GITHUB_TOKEN }}
      run: gh release download ${{ inputs.version }}
    - name: check if file is downloaded
      run : ls