name: Reusable workflow example

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version: 
        required: true
        type: string

jobs:
  application-version:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: first one
      run: |
        echo "inputs.environment : ${{ inputs.environment }}"
    - name: second one
      run: |
        echo "vars.hello_world : ${{ vars.HELLO_WORLD }}"