name: Reusable workflow example

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  application-version:
    environment: inputs.version
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ inputs.version }}
    - run: |
        echo ${{ vars.STORM_FE_APP_SERVICE_NAME }}