name: Reusable workflow example

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  application-version:
    environment: inputs.environment
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ inputs.environment }}
    - run: |
        echo ${{ vars.HELLO_WORLD }}