
name: CI

on:
    
  issues: 
    types: [opened, edited]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
      environment: ${{ steps.extract_version.outputs.environment }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.13.1' 
      - run: cd extract && go test
      - env:
          ISSUE: ${{ github.event.issue.body }}
        run: cd extract && echo $ISSUE | go run cmd/main.go
      - id: extract_version
        env:
          ISSUE: ${{ github.event.issue.body }}
        run: echo "environment=$(echo "$ISSUE" | go run cmd/main.go -version)" >> "$GITHUB_OUTPUT"
        working-directory: extract
      - env:
          ISSUE: ${{ github.event.issue.body }}
        run: go run cmd/main.go $ISSUE
        working-directory: extract
  close-issue:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ needs.build.outputs.environment }}




        





