
name: CI

on:
    
  issues: 
    types: [opened, edited]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
      environment: ${{ steps.extract_version.outputs.environment }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.13.1' 
      - run: cd extract && go mod download
      - run: go test
      - env:
          ISSUE: ${{ github.event.issue.body }}
        run: echo $ISSUE | go run cmd/main.go




        





