# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
    
  issues: 
    types: [opened, edited]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
      environment: ${{ steps.extract_version.outputs.environment }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - id: issuetext
        env: 
          ISSUE: ${{ github.event.issue.body }}
        run : |
            echo body="$ISSUE" >> $GITHUB_OUTPUT
            
      - uses: actions/github-script@v7
        name: Getting application version number
        id: storm-version
        with:
          result-encoding: string
          script: |
            const text = "${{ steps.issuetext.outputs.body }}"
            const versionRegex = /Version v(\d+\.\d+\.\d+)/;
            const versionMatch = text.match(versionRegex);
            const version = versionMatch ? versionMatch[1] : "Version not found";
            console.log(version);
            return version

      - uses: actions/github-script@v7
        name: Getting deployment environment
        id: deployment-environment
        with:
          result-encoding: string
          script: |
            const text = "${{ steps.issuetext.outputs.body }}"
            const envRegex = /### Environment\s+(\w+)/;
            const envMatch = text.match(envRegex);
            const env = envMatch ? envMatch[1] : "Environment not found";
            console.log(env)
            return env

  #verify_output:
  #  needs: [build]
  #  runs-on: ubuntu-latest
  #  steps:
  #    - run: echo ${{ needs.build.outputs.version }} ${{ needs.build.outputs.environment }}

  #calling:
  #  needs: build
  #  uses: ./.github/workflows/callable-workflow.yml
  #  if: ${{ needs.build.outputs.output2 == 'ute' }} 
  #  with:
  #    environment: 'ute'
  #    version: '1.2.4'




        





