# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
    
  issues: 
    types: [opened]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.set-deployment-env.outputs.result }}
      output3: ${{ steps.set-result.outputs.result }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Setting issue body
        id: step_one
        env:
          issue: ${{ github.event.issue.body }}
        run: |
          echo $issue
          echo issue=$issue >> "$GITHUB_OUTPUT"

      - name: Use the value
        id: step_two
        run: |
          echo "${{ steps.step_one.outputs.issue }}"

      - uses: actions/github-script@v7
        name: getting application version number
        id: set-result
        with:
          result-encoding: string
          script: |
            const text = "${{ steps.step_one.outputs.issue }}"
            const versionRegex = /Version v(\d+\.\d+\.\d+)/;
            const versionMatch = text.match(versionRegex);
            const version = versionMatch ? versionMatch[1] : "Version not found";
            console.log(`Version: ${version}`);
            return version

      - uses: actions/github-script@v7
        name: getting deployment environment
        id: set-deployment-env
        with:
          result-encoding: string
          script: |
            const text = "${{ steps.step_one.outputs.issue }}"
            const envRegex = /Environment (\w+) \(/;
            const envMatch = text.match(envRegex);
            const env = envMatch ? envMatch[1] : "Environment not found";
            console.log(`deployenv=${env}`) //>> "$GITHUB_OUTPUT";
            return env

      - id: step1
        run: echo "test=world" >> "$GITHUB_OUTPUT"

  testing:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - env:
          OUTPUT1: ${{needs.build.outputs.output1}} 
          OUTPUT2: ${{needs.build.outputs.output2}}
          OUTPUT3: ${{needs.build.outputs.output3}}
        run: echo "$OUTPUT1 -- $OUTPUT2 -- $OUTPUT3" 

  calling:
    needs: build
    uses: ./.github/workflows/callable-workflow.yml
    if: ${{ needs.build.outputs.output2 == 'ute' }} 
    with:
      environment: 'ute'
      version: ${{ needs.build.outputs.output3 }} 




        





